# Generated by Django 4.0.5 on 2022-06-27 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상품명')),
                ('image', models.FileField(upload_to='productimg', verbose_name='썸네일')),
                ('dec', models.TextField(verbose_name='상품설명')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='노출 종료일')),
                ('is_active', models.BooleanField(verbose_name='활성화 여부')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': '상품',
            },
        ),
    ]
