# Generated by Django 4.0.5 on 2022-06-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='아티클',
        ),
        migrations.AlterModelTable(
            name='category',
            table='카테고리',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='댓글',
        ),
    ]
