# Generated by Django 4.0.5 on 2022-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=130, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=50, verbose_name='유저이름')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
