# Generated by Django 4.0.5 on 2022-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hobby_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('남', '남'), ('여', '여')], max_length=10, verbose_name='성별'),
        ),
    ]
